### ISSUE TITLE
ffsubsync stopped working with autosubsync after Python 3.10 upgrade

### ISSUE THREAD

**Issue by bxkx** [Ajatt-Tools/autosubsync-mpv#3]
Ever since Arch got the Python 3.10 update a few days ago, ffsubsync doesn't work with autosubsync script anymore. Alass is still working, though.
I'm using Celluloid. If I run ffsubsync from the terminal it does work however. python-ffsubsync etc is all from the AUR.

Here's the logs I'm getting when trying to use it with autosubsync:

```
[cplayer] Run command: script-binding, flags=73, args=[name="modules/Enter"]
[modules] [14:24:01] INFO     extracting speech segments from reference   ffsubsync.py:329
[modules]                     '/home/user/movie.mkv'...                                 
[modules] Traceback (most recent call last):
[modules]   File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 568, in _build_master
[modules]     ws.require(__requires__)
[modules]   File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 886, in require
[modules]     needed = self.resolve(parse_requirements(requirements))
[modules]   File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 777, in resolve
[modules]     raise VersionConflict(dist, req).with_context(dependent_req)
[modules] pkg_resources.ContextualVersionConflict: (auditok 0.2.0 (/usr/lib/python3.10/site-packages), Requirement.parse('auditok==0.1.5'), {'ffsubsync'})
[modules] During handling of the above exception, another exception occurred:
[modules] Traceback (most recent call last):
[modules]   File "/usr/bin/ffsubsync", line 33, in <module>
[modules]     sys.exit(load_entry_point('ffsubsync==0.4.16', 'console_scripts', 'ffsubsync')())
[modules]   File "/usr/lib/python3.10/site-packages/ffsubsync/ffsubsync.py", line 444, in main
[modules]     return run(args)['retval']
[modules]   File "/usr/lib/python3.10/site-packages/ffsubsync/ffsubsync.py", line 330, in run
[modules]     reference_pipe.fit(args.reference)
[modules]   File "/usr/lib/python3.10/site-packages/ffsubsync/sklearn_shim.py", line 221, in fit
[modules]     self._final_estimator.fit(Xt, y, **fit_params)
[modules]   File "/usr/lib/python3.10/site-packages/ffsubsync/speech_transformers.py", line 242, in fit
[modules]     detector = _make_webrtcvad_detector(self.sample_rate, self.frame_rate, self._non_speech_label)
[modules]   File "/usr/lib/python3.10/site-packages/ffsubsync/speech_transformers.py", line 117, in _make_webrtcvad_detector
[modules]     import webrtcvad
[modules]   File "/usr/lib/python3.10/site-packages/webrtcvad.py", line 1, in <module>
[modules]     import pkg_resources
[modules]   File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3243, in <module>
[modules]     def _initialize_master_working_set():
[modules]   File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3226, in _call_aside
[modules]     f(*args, **kwargs)
[modules]   File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3255, in _initialize_master_working_set
[modules]     working_set = WorkingSet._build_master()
[modules]   File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 570, in _build_master
[modules]     return cls._build_from_requirements(__requires__)
[modules]   File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 583, in _build_from_requirements
[modules]     dists = ws.resolve(reqs, Environment())
[modules]   File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 772, in resolve
[modules]     raise DistributionNotFound(req, requirers)
[modules] pkg_resources.DistributionNotFound: The 'auditok==0.1.5' distribution was not found and is required by ffsubsync
[modules] Subtitle synchronization failed. 
```

**Comment by tatsumoto-ren** [comment]
It works for me. Try updating ffsubsync and/or audiotok
```
$ pip install --upgrade ffsubsync
```

**Comment by bxkx** [comment]
That did the trick, thanks!
